#!/usr/bin/env bash
# install engine x web server in a new ubuntu server
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# echo "Hello World!" | sudo tee /var/www/html/index.html
# OR
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restar
