#!/usr/bin/env bash
# Configure Nginx to return the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx

# Get the hostname and save it in a variable
HOSTNAME=$(hostname)

# Add the custom header with the hostname
sudo sed -i "48i\\\tadd_header X-Served-By \"$HOSTNAME\";\n" /etc/nginx/sites-available/default

# Create sample HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'\''est pas une page\\n" | sudo tee /var/www/html/404.html

sudo service nginx restart
