#!/usr/bin/env bash
# Check if Nginx is running
if ! pgrep nginx; then  
  service nginx start
fi
# Check if port 80 is exposed
if ! netstat -anp | grep nginx | grep 80; then
  service nginx restart --publish 80:80
fi
