#!/usr/bin/env bash
# This script creates a file containing its PID at /var/run/myscript.pid
# It displays "To the moon and back" indefinitely
# It displays "I dislike the kill command" when receiving a SIGTERM signal
# It displays "Why don't you love me?" when receiving a SIGINT signal
# It deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

delete_file()
{
	rm /var/run/myscript.pid
	exit
}

while true
do
  echo "To the moon and back"
  sleep 2
  trap 'echo "Why dont you love me?"' SIGINT
  trap 'echo "I dislike the kill command" && delete_file' SIGTERM
  trap 'delete_file' SIGQUIT
done
