#!/usr/bin/env bash
# Manages the program called manage_my_process

FILE="/var/run/my_process.pid"

create() {
    echo $$ | sudo tee $FILE >/dev/null
}

if [ "$1" == "start" ]; then
    create
    ./manage_my_process &
    echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
    if [ -e "$FILE" ]; then
        sudo pkill -f "./manage_my_process"
        sudo rm $FILE
    fi
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then
    $0 stop >/dev/null 2>&1
    $0 start >/dev/null 2>&1
    echo "manage_my_process restarted"

else
    echo "Usage: $0 {start|stop|restart}"
fi
