#!/usr/bin/env bash
# This script stops 4-to_infinity_and_beyond process

# Get process ID of the 4-to_infinity_and_beyond process
pid=$(pgrep 4-to_infinity_and_beyond)

# Use kill command to stop process
kill "$pid"
