#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Send a SIGTERM signal to the process to terminate it
kill -s SIGTERM "$pid"
