#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration
# and displays "I am invincible!!!" when receiving a SIGTERM signal

handle_sigterm() {
    echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
