#!/usr/bin/env bash



# script creates the file /var/run/myscript.pid containing its PID
# Displays "To infinity and beyond" indefini
# Displays "I hate the kill command" when receiving SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

delete_func() {
    rm /var/run/myscript.pid
    exit
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; delete_func' SIGTERM
trap 'delete_func' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
