#!/usr/bin/env bash
# This script writes "I am alive!" to /tmp/my_process indefinitely with a 2-second pause between each message

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
